# Problem set 0

This is the first problem set. Line break here <br>
*Testing of markdown* - line break<br>
**More testing** should now be same line
***EVEN MORE***
### Headers automatically make linebreaks
Something something


In [5]:
a = 1
b = 2
c = a + b
print(c)

3


In [9]:
#slicing
x = [i for i in range(6)] #same as x = [0,1,2,3,4,5]
print(x[:2])
print(x[2:])


[0, 1]
[2, 3, 4, 5]


In [21]:
x = [1,2,3]
z = [i for i in x] # generates a new list from the elements in x
y = x # references to the same list as x / y points to the same object as x.
y[-1] = 4
print(x)
print(z)

[1, 2, 4]
[1, 2, 3]


The above code shows how Python handles references. x references a list [1,2,3] and y does the same. The ease of use is declaring y = x which is effectively the same as pointing to the same locating in memory. 

In [20]:
for i in range(5):
    if i >= 2: break
    print(i)

0
1


In [23]:
for i in range(5):
    if i == 2:
        continue
    print(i)

0
1
3
4


In [27]:
x = 3
if x > 3:
    print("too big")
elif x < 1:
    print("too small")
else:
    print("just right")

just right


In [33]:
a = 1
def f(x):
    return x+a

def g(x, a=1):
    return x+a

print(f(1))
print(g(1))
a=2
print(f(1))
print(g(1))

2
2
3
2


In [44]:
import numpy as np 

print(0.1 + 0.2)
print(0.1 + 0.2 == 0.3)
print(0.5+0.5)
print(0.5 + 0.5 == 1.0)
print(np.isclose(0.1+0.2,0.3)) #numpy way of handling floating point numbers
print(np.isclose(1e-200*1e200*1e200*1e-200,1.0))
print(np.isinf(1e-200*(1e200*1e200)*1e-200))
print(np.isclose(1e200*(1e-200*1e-200)*1e200 ,0.0))

0.30000000000000004
False
1.0
True
True
True
True
True


In [53]:
x = np.array([1,2,3])
y = x
x += 1
print(x)
x[:] = x + 1
print(x)
x = x + 1
print(x)
print(y)

[2 3 4]
[3 4 5]
[4 5 6]
[3 4 5]


In [55]:
class SquareClass:
    def __init__(self, length, width):
        self.length = length
        self.width = width
    
    def size(self):
        return self.length*self.width
    
square = SquareClass(2,2)
print(square.size())

4
